pipeline {
agent { label 'windows_worker' }
  stages {
    stage('Build') {
      steps {
        dir("dotnet/src") {
          echo 'Building..'
          bat 'C:\\Program files (x86)\\Microsoft visual studio\\2019\\Buildtools\\msbuild\\Current\\bin\\msbuild.exe inside.domipay.vn\\Inside.Domipay.Service\\Inside.Domipay.Service.csproj'
      }
    }
    stage('Test') {
      steps {
        echo 'Testing..'
      }
    }
    stage('Deploy') {
      steps {
        echo 'Deploying....'
      }
    }
  }
}
