pipeline {
agent { label 'windows_worker' }
  stages {
    stage('Build') {
      steps {
        dir("dotnet/src") {
          echo 'Building..'
          bat "\"C:\\Program files (x86)\\Microsoft visual studio\\2019\\Buildtools\\msbuild\\Current\\bin\\msbuild.exe\" inside.domipay.vn\\Inside.Domipay.Service\\Inside.Domipay.Service.csproj"
        }
      }
    }
    stage ('Stash from worker build'){
        steps {
            dir('dotnet/src/inside.domipay.vn/Inside.Domipay.Service/bin/Debug/') {
                stash name: "artifact", includes: "*.dll"
            }
        }
    }  
    stage('Test') {
      steps {
        echo 'Testing..'
      }
    }
}
stage('unstash and deploy') {
    agent { label 'master' }
    stages {
        stage('Unstash on master') {
            steps {
                dir('/data/src') {
                    unstash "artifact"
                }
            }
        }
    }    
    stages('Deploy') {
      steps {
        echo 'Deploying....'
      }
    }
  }
}
